In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split

In [3]:
# df1 = pd.read_csv("all_escalations.csv",encoding = 'ISO-8859-1')
df = pd.read_csv("Escalation Prediction Data.csv",encoding = 'ISO-8859-1')
# df1.drop_duplicates(subset = ['CaseNumber'],inplace = True)
# print(df1.shape)
# df1.head()

In [82]:
df['Instance'].isna().sum()

281

In [83]:
# df2 = pd.read_csv("non_escalated.csv",encoding = 'ISO-8859-1')
# print(df2.shape)
# df2.head()

In [84]:
# dropping_list = []
# for i in range(0,6000):
#     drop_indices = np.random.choice(df2.index,replace=False)
#     dropping_list.append(drop_indices)
# # print(dropping_list)
# df2.drop(df2.index[dropping_list],inplace = True)

In [85]:
# df = pd.concat((df1,df2))
# print(df.shape)
# df.head()

In [86]:
# df_dup = df[df['CaseNumber'].duplicated()]
# df_dup.shape

In [87]:
# columns_to_drop = ['ID','Billable','CreditCard','TACu','RFORequested','RFOAvailable','MasterCase','CriticalAccount','CreditTotal','AgentCoached','CaseNumber','AccountID','AccountSTID','ATEscalatedBy','AtRiskIndicator','AtRiskSituationID','NPSScore','ClosedDate','ContactID','ContactName','ContactPhone','CreatedByID','CreatedDate','Description','DynamicPortalLink','EndUserID','LastModifiedByID','LastModifiedDate','LastSLAUpdateTACAgent','NextMilestoneDueDate','OrderNumber','PartnerSTID','PortalAccountDetails','RecordTypeID','Resolution','ScheduledDate','ServiceAgreementProcessEndTime','ServiceAgreementProcessStartTime','SkyLegacyID','SLAFlag','Status','ValidEscalation','Escalated','ReasonEscalated','DateEscalated','ATEscalatedDate','EscalateToSystems','EscalateToNetworks','EscalationMonth','OwnerId']
# df.drop(columns=columns_to_drop,inplace=True)

In [88]:
# allnacols = (df.isna().sum()/len(df))*100
# print(len(allnacols[allnacols >= 70].index))
# df.drop(columns = allnacols[allnacols >=70].index,inplace = True)
# df.head()

In [4]:
final_df = df[['Escalation Phrases','Reopen','Response Time in min','Reopen Counter','Total Comments','Total Agents','Case Age','Instance','MilestoneIcon','ActiveServiceAgreement','CaseReason','AtRisk','ATEscalation']]
# final_df = df[['Reopen','Reopen Counter','Total Comments','Total Agents','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater','ATEscalation']]
#CaseOrigin

In [5]:
cols = ['Reopen','Instance','ActiveServiceAgreement','CaseReason','AtRisk','MilestoneIcon']
# cols = ['Reopen','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
for c in cols:
    final_df[c].fillna('Unknown',inplace=True)

C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py:6287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [6]:
# final_df['smx_case_no_of_days'].fillna(method='ffill',inplace=True)

In [7]:
final_df['Response Time in min'] = final_df.groupby("ATEscalation")['Response Time in min'].transform(lambda x: x.fillna(x.mean()))
final_df['Case Age'] = final_df.groupby("ATEscalation")['Case Age'].transform(lambda x: x.fillna(x.mean()))

C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [8]:
# lbl = LabelEncoder() 
# lbl.fit(list(final_df['ATEscalation'].values)) 
# final_df['ATEscalation'] = lbl.fit_transform(list(final_df['ATEscalation'].values))

In [9]:
mean = final_df['Response Time in min'].mean()
std = final_df['Response Time in min'].std()
final_df['Response Time in min'] = final_df['Response Time in min'].apply(lambda x:(x-mean)/std)

C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
mean = final_df['Case Age'].mean()
std = final_df['Case Age'].std()
final_df['Case Age'] = final_df['Case Age'].apply(lambda x:(x-mean)/std)

C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
final_df

Escalation Phrases  Reopen  Response Time in min  Reopen Counter  \
0                      4   False             -0.667083               0   
1                      1   False             -0.678899               0   
2                     12   False             -0.700669               0   
3                      0   False             -0.680626               0   
4                      0   False              0.250854               0   
...                  ...     ...                   ...             ...   
4749                   0   False             -0.198829               0   
4750                   0   False              2.811724               0   
4751                   0   False             -0.198829               0   
4752                   0   False             -0.198829               0   
4753                   8    True              2.092730               1   

      Total Comments  Total Agents  Case Age Instance MilestoneIcon  \
0                  9             2 -0.108216      OLA           RED   
1                 14             1  0.046607      ELI           RED   
2                 29             4 -0.108216  Unknown           RED   
3                 12             4  0.459466      ZOE           RED   
4                  0             0 -0.245835      KIP           RED   
...              ...           ...       ...      ...           ...   
4749               0             0 -0.245835      N08         GREEN   
4750               2             2 -0.228633      ZED         GREEN   
4751               0             0 -0.211430      ZED         GREEN   
4752               0             0 -0.228633      JAK           RED   
4753               2             2 -0.228633      DEB         GREEN   

        ActiveServiceAgreement           CaseReason  \
0                       Direct          Add Service   
1                       Direct               Change   
2                       Direct              Problem   
3                       Direct               Outage   
4                       Direct              Problem   
...                        ...                  ...   
4749                    Direct  Account Maintenance   
4750                    Direct  Account Maintenance   
4751  PARTNER SUPPORT, 5 YR NP          Add Service   
4752                    Direct  Account Maintenance   
4753                    Direct               Outage   

                                                 AtRisk  ATEscalation  
0                                       At Risk 3 Times             1  
1                                        At Risk 1 Time             1  
2     <img src="http://free-121d5f44d20-121d603d1c5-...             1  
3                                        At Risk 1 Time             1  
4                                        At Risk 1 Time             1  
...                                                 ...           ...  
4749                                    Healthy Account             0  
4750                                    Healthy Account             0  
4751                                    Healthy Account             0  
4752                                    Healthy Account             0  
4753                                    At Risk 2 Times             1  

[4754 rows x 13 columns]

In [12]:
# cols = ['AccountName','AccountTeam','CaseReason','Feature','ActiveServiceAgreement','ServiceAgreementForCase','AtRisk','SubStatus','SubReason','Priority','Instance','MilestoneStatus','SubFeature','Theater']
# cols = ['Reopen','AccountName','AccountTeam','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
# for c in cols:
#     enc = OneHotEncoder(handle_unknown='ignore')
#     temp_col = pd.get_dummies(final_df[c])
#     temp_col = pd.DataFrame(enc.fit_transform(final_df[[c]],).toarray())
#     final_df.drop(columns=[c],inplace=True)
#     final_df = final_df.join(temp_col)
#     final_df.drop(columns=[c],inplace=True)
#     final_df = pd.concat((final_df,temp_col),axis=1)
    
# final_df = pd.concat((final_df,y),axis=1)

In [13]:
cols = ['Reopen','CaseReason','Instance','ActiveServiceAgreement','AtRisk','MilestoneIcon']
# cols = ['Reopen','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
temp_df = final_df[['Reopen','Instance','ActiveServiceAgreement','AtRisk','MilestoneIcon']]
# temp_df = final_df[['Reopen','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']]
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(temp_df.values)
temp_df = pd.DataFrame(enc.transform(temp_df.values).toarray())
for c in cols:
    final_df.drop(columns=[c],inplace=True)
final_df = final_df.join(temp_df)
final_df

C:\Users\maheshan\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Escalation Phrases  Response Time in min  Reopen Counter  \
0                      4             -0.667083               0   
1                      1             -0.678899               0   
2                     12             -0.700669               0   
3                      0             -0.680626               0   
4                      0              0.250854               0   
...                  ...                   ...             ...   
4749                   0             -0.198829               0   
4750                   0              2.811724               0   
4751                   0             -0.198829               0   
4752                   0             -0.198829               0   
4753                   8              2.092730               1   

      Total Comments  Total Agents  Case Age  ATEscalation    0    1    2  \
0                  9             2 -0.108216             1  1.0  0.0  0.0   
1                 14             1  0.046607             1  1.0  0.0  0.0   
2                 29             4 -0.108216             1  1.0  0.0  0.0   
3                 12             4  0.459466             1  1.0  0.0  0.0   
4                  0             0 -0.245835             1  1.0  0.0  0.0   
...              ...           ...       ...           ...  ...  ...  ...   
4749               0             0 -0.245835             0  1.0  0.0  0.0   
4750               2             2 -0.228633             0  1.0  0.0  0.0   
4751               0             0 -0.211430             0  1.0  0.0  0.0   
4752               0             0 -0.228633             0  1.0  0.0  0.0   
4753               2             2 -0.228633             1  0.0  1.0  0.0   

      ...   90   91   92   93   94   95   96   97   98   99  
0     ...  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1     ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
2     ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
3     ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4     ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
4749  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
4750  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
4751  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  
4752  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
4753  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[4754 rows x 107 columns]

In [14]:
y = final_df['ATEscalation']
final_df.drop(columns=['ATEscalation'],inplace=True)

In [15]:
# cols=final_df.shape[1]
# X=final_df.iloc[:,0:cols-1].values
# y=final_df.iloc[:,cols-1:cols].values

In [16]:
y_s = y.ravel()

In [17]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_test, y_train, y_test = train_test_split(final_df.values, y, test_size=0.2,stratify = y_s)

In [18]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression(random_state=0, solver='liblinear',max_iter=200,C=0.5)
log_fit = log_clf.fit(X_train,y_train)
pred = log_clf.predict(X_test)

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(max_depth=25,min_samples_split=4,criterion = 'entropy',random_state=0)
rf_clf.fit(X_train,y_train)
pred = rf_clf.predict(X_test)

In [20]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
svm_clf = make_pipeline(StandardScaler(), SVC(gamma='auto',probability=True))
svm_clf.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=True,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [21]:
import xgboost as xgb
xg_clf = xgb.XGBClassifier(booster='dart',objective="binary:logistic", random_state=42)
xg_clf.fit(X_train,y_train)
pred = xg_clf.predict(X_test)

In [22]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
# X, y = make_classification(n_samples=1000, n_features=4,n_informative=2, n_redundant=0,random_state=0)
ada_clf = AdaBoostClassifier(n_estimators=100, random_state=0)
ada_clf.fit(X_train,y_train)
pred = ada_clf.predict(X_test)

In [56]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train,y_train)
pred = clf.predict(X_test)

In [23]:
accuracy = clf.score(X_test,y_test)
print(accuracy*100)

NameError: name 'clf' is not defined

In [113]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, pred)

(array([0.92965779, 0.90117647]),
 array([0.92090395, 0.91190476]),
 array([0.92526017, 0.90650888]),
 array([531, 420], dtype=int64))

In [114]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred, labels=[0,1])

array([[489,  42],
       [ 37, 383]], dtype=int64)

In [115]:
# import matplotlib.pyplot as plt
# features = ['Reopen','Response Time in min','Reopen Counter','Total Comments','Total Agents','Instance','MilestoneIcon','ActiveServiceAgreement','AtRisk','Theater']
# importances = clf.feature_importances_
# importances = importances[:7]
# print(len(importances))
# # indices = np.argsort(importances)

# plt.bar([x for x in range(len(importances))], importances)
# plt.show()

In [116]:
##########################################################################

In [117]:
# test_data = pd.read_csv('daily_test_data.csv',encoding = 'ISO-8859-1')
# test_data = test_data.drop_duplicates(subset = ['CaseNumber']).reset_index(drop=True)
# print(test_data.shape)
# test_data

In [49]:
test_data = pd.read_csv('Test_data.csv',encoding = 'ISO-8859-1')
test_data.drop_duplicates(subset = ['CaseNumber'],inplace = True)
print(test_data.shape)
test_data.head()

(1225, 36)


Unnamed: 0  CaseNumber  Reopen  Reopen Counter  Case Age  \
0           0     3328682   False             0.0       6.0   
1           1     3328483    True             1.0       6.0   
2           2     3328662   False             0.0       6.0   
3           3     3328470   False             0.0       6.0   
4           4     3328669   False             0.0       6.0   

  ActiveServiceAgreement                         AccountName AccountTeam  \
0                 Direct                        Solutions II      Silver   
1                 Direct                       Hodge Company      Bronze   
2                 Direct  Little Spurs Pediatric Urgent Care      Silver   
3                 Direct               Shobe Financial Group      Bronze   
4                 Direct                            InstaMed    Platinum   

            AtRisk  AtRiskIndicator  ...                             Subject  \
0  Healthy Account            False  ...  Carlos Ortega - 1265 After exactly   
1  Healthy Account            False  ...                        Number issue   
2  Healthy Account            False  ...              Account - Block number   
3  Healthy Account            False  ...                Call flow correction   
4   At Risk 1 Time            False  ...             User - Softphone Issues   

            AccountId Region PartnerOfRecordCloud Response Time in min  \
0  0010h00001cv7U5AAI    USA   001C000000rPTB8IAO            24.533333   
1  0010h00001cxOlGAAU    USA   0010h00001Zb7LjAAJ            20.183333   
2  0011A00001SOHbRQAX    USA   001C000001Lxu10IAB             5.666667   
3  001C0000019C4cGIAS    USA   001C000000rPSp1IAG           316.800000   
4  001C000001NBbB8IAL    USA                  NaN                  NaN   

  Total Comments Total Agents   Last Response Date Case Age__C  \
0              4            2  2020-06-22 19:31:56           5   
1              7            2  2020-06-23 12:33:06           5   
2             10            3  2020-06-24 21:16:09           5   
3              4            3  2020-06-24 01:38:13           5   
4              0            0                  NaN           5   

  Escalation Phrases  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  

[5 rows x 36 columns]

In [26]:
casenumbers = test_data['CaseNumber'].values

In [27]:
# test_data = test_data[['Reopen','Reopen Counter','Total Comments','Total Agents','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater','ATEscalation']]
test_data = test_data[['Escalation Phrases','Reopen','Response Time in min','Reopen Counter','Total Comments','Total Agents','Case Age','Instance','AtRisk','CaseReason','MilestoneIcon','ActiveServiceAgreement']]

In [28]:
cols = ['AtRisk','MilestoneIcon','CaseReason','Instance','ActiveServiceAgreement']
# cols = ['AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
for c in cols:
    test_data[c].fillna('Unknown',inplace=True)
# test_data['smx_case_no_of_days'].fillna(method='ffill',inplace=True)

In [29]:
test_data['Response Time in min'] = test_data['Response Time in min'].transform(lambda x: x.fillna(x.mean()))
test_data['Case Age'] = test_data['Case Age'].transform(lambda x: x.fillna(x.mean()))

In [30]:
mean = test_data['Response Time in min'].mean()
std = test_data['Response Time in min'].std()
test_data['Response Time in min'] = test_data['Response Time in min'].apply(lambda x:(x-mean)/std)

In [31]:
mean = test_data['Case Age'].mean()
std = test_data['Case Age'].std()
test_data['Case Age'] = test_data['Case Age'].apply(lambda x:(x-mean)/std)

In [32]:
# lbl = LabelEncoder() 
# # lbl.fit(list(final_df['ATEscalation'].values)) 
# test_data['ATEscalation'] = lbl.fit_transform(list(test_data['ATEscalation'].values))

In [33]:
# cols = ['AccountName','AccountTeam','CaseReason','Feature','ActiveServiceAgreement','ServiceAgreementForCase','AtRisk','SubStatus','SubReason','Priority','Instance','MilestoneStatus','SubFeature','Theater']
# cols = ['AccountName','AccountTeam','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
# test_y = test_data['ATEscalation']
# test_data.drop(columns=['ATEscalation'],inplace=True)
# for c in cols:
#     temp_col = pd.get_dummies(test_data[c])
#     test_data.drop(columns=[c],inplace=True)
#     test_data = pd.concat((test_data,temp_col),axis=1)
    
# test_data = pd.concat((test_data,test_y),axis=1)

In [34]:
cols = ['Reopen','Instance','CaseReason','AtRisk','MilestoneIcon','ActiveServiceAgreement']
# cols = ['Reopen','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']
temp_df = test_data[['Reopen','Instance','AtRisk','MilestoneIcon','ActiveServiceAgreement']]
# temp_df = test_data[['Reopen','AccountName','CaseReason','Feature','ActiveServiceAgreement','AtRisk','SubReason','Priority','Instance','MilestoneIcon','SubFeature','Theater']]
temp_df = pd.DataFrame(enc.transform(temp_df.values).toarray())
for c in cols:
    test_data.drop(columns=[c],inplace=True)
test_data = test_data.join(temp_df)

In [35]:
# test_data = test_data.head(-15)
test_data

Escalation Phrases  Response Time in min  Reopen Counter  \
0                      0         -7.469762e-01             0.0   
1                      0         -7.576377e-01             1.0   
2                      1         -7.932168e-01             0.0   
3                      0         -3.065601e-02             0.0   
4                      0         -1.253864e-15             0.0   
...                  ...                   ...             ...   
1220                   0         -1.253864e-15             0.0   
1221                   0          1.984321e+00             0.0   
1222                   0         -1.253864e-15             0.0   
1223                   0         -7.801452e-01             0.0   
1224                   0         -1.253864e-15             0.0   

      Total Comments  Total Agents  Case Age    0    1    2    3  ...   90  \
0                  4             2 -0.336568  1.0  0.0  0.0  0.0  ...  0.0   
1                  7             2 -0.336568  0.0  1.0  0.0  0.0  ...  0.0   
2                 10             3 -0.336568  1.0  0.0  0.0  0.0  ...  0.0   
3                  4             3 -0.336568  1.0  0.0  0.0  0.0  ...  0.0   
4                  0             0 -0.336568  1.0  0.0  0.0  0.0  ...  0.0   
...              ...           ...       ...  ...  ...  ...  ...  ...  ...   
1220               0             0 -0.400884  1.0  0.0  0.0  0.0  ...  0.0   
1221               5             4 -0.400884  1.0  0.0  0.0  0.0  ...  0.0   
1222               0             0 -0.375157  1.0  0.0  0.0  0.0  ...  0.0   
1223               5             2 -0.375157  1.0  0.0  0.0  0.0  ...  0.0   
1224               0             0 -0.375157  1.0  0.0  0.0  0.0  ...  0.0   

       91   92   93   94   95   96   97   98   99  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  
1220  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1221  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1222  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1223  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1224  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1225 rows x 106 columns]

In [36]:
# test_y = test_data['ATEscalation']
# test_data.drop(columns=['ATEscalation'],inplace=True)

In [37]:
log_pred = log_clf.predict(test_data.values) 
rf_pred = rf_clf.predict(test_data.values)
xg_pred = xg_clf.predict(test_data.values)
svm_pred = svm_clf.predict(test_data.values)
ada_pred = ada_clf.predict(test_data.values)

In [38]:
log_prob = log_clf.predict_proba(test_data.values) 
log_prob = np.max(log_prob,axis=1)
rf_prob = rf_clf.predict_proba(test_data.values) 
rf_prob = np.max(rf_prob,axis=1)
xg_prob = xg_clf.predict_proba(test_data.values) 
xg_prob = np.max(xg_prob,axis=1)
svm_prob = svm_clf.predict_proba(test_data.values) 
svm_prob = np.max(svm_prob,axis=1)
ada_prob = ada_clf.predict_proba(test_data.values) 
ada_prob = np.max(ada_prob,axis=1)

In [39]:
# from sklearn.metrics import precision_recall_fscore_support
# precision_recall_fscore_support(test_y, pred)

In [40]:
# accuracy = clf.score(X_test,y_test)
# print(accuracy*100)

In [41]:
# from sklearn.metrics import confusion_matrix
# confusion_matrix(test_y, pred, labels=[0,1])

In [42]:
#########################################################################

In [43]:
# output = pd.DataFrame(pred,columns=["Output"])
# output.to_csv("ANZ Output.csv")

In [44]:
print(xg_pred,log_pred,rf_pred,svm_pred,ada_pred)

[0 1 0 ... 0 0 1] [1 1 1 ... 1 1 1] [0 1 1 ... 1 0 1] [1 1 1 ... 1 1 1] [1 1 1 ... 1 1 1]


In [45]:
print(xg_prob,log_prob,rf_prob,svm_prob,ada_prob)

[0.82477844 0.96151084 0.54669434 ... 0.5850285  0.9641543  0.94365185] [0.6717408  0.99330502 0.64798435 ... 0.64015106 0.60086125 0.91119839] [0.68693264 0.84802381 0.50223636 ... 0.55904427 0.72301642 0.61064667] [0.87360201 0.99007215 0.65266244 ... 0.87554206 0.88520586 0.94282355] [0.50398063 0.51713867 0.50049099 ... 0.50532989 0.58465473 0.50944956]


In [47]:
df = pd.DataFrame({'CaseNumber':casenumbers,'XG Boost':xg_pred,'Logistic':log_pred,'Random Forest':rf_pred,'SVM':svm_pred,'AdaBoost':ada_pred,
                  'XGBoost_Prob':xg_prob,'Logistic_Prob':log_prob,'Random Forest_Prob':rf_prob,'SVM_Prob':svm_prob,'AdaBoost_Prob':ada_prob})
df.shape

(1225, 11)

In [50]:
final_df = test_data.merge(df,on='CaseNumber',how='left')

In [51]:
final_df.to_csv("APAC and US Prediction Output.csv")

In [164]:
import joblib

filename = 'xg_model.sav'
joblib.dump(xg_clf, filename)

['xg_model.sav']

In [159]:
loaded_model = joblib.load(filename)
result = loaded_model.predict(test_data.values)
print(result)

[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1]
